# Generated by Django 3.0.5 on 2020-05-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mymodel_tz_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
