# Generated by Django 3.0.5 on 2020-05-02 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_mymodel_is_paid"),
        ("myapp", "0003_mymodel_is_active"),
    ]

    operations = []
