name: linters
on: [push]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - uses: actions/cache@v2
        with:
          path: .venv/
          key: ${{ runner.os }}-py3.6-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-py-
      - name: Install Dependencies
        run: |
          pip install --upgrade pip poetry
          poetry config virtualenvs.in-project true
          poetry install
      - name: Run linters
        uses: pre-commit/action@v2.0.0
